## Primer

The goal of this project is to investigate any potential correlation between human activity and a potential rise in fires over the past decades, both from arson and environmental affects caused by human activities. Forests are incredibly important as carbon sinks and oxygen producers on earth, so their health is also our health.

To tackle this issue, we will be incorporating data from the Oregon Fire Department as well as Kaggle, from US Census data, in order to put together a view of what fires have occurred in the past 20 to 25 years, and see if their rate has increased, as well as use data methods to determine how weather and human activity could have directly or indirectly affected their formation and time to be contained.

## Modules

The modules we will be importing are seaborn, matplotlib.pyplot, pandas, warnings, and numpy. We will need pandas to construct our DataFrame, and seaborn and matplotlib to plot and help navigate our data in more visual ways. numpy will also assist in these, and warnings will serve to show any potential errors in the code. operating system (os) will allow us to access the file, getting around some finicky issues with the notebook. importing regex will allow us to more accurately filter through string objects.

In [32]:
import seaborn as sns
import numpy as np
import re
import matplotlib.pyplot as plt
import pandas as pd
import os
import warnings

In [33]:
os.getcwd()

'/home/jovyan/data271_sp26/lab/lab08/final project folder'

In [34]:
os.listdir()

['finalProj.ipynb',
 '.ipynb_checkpoints',
 'ODF_Fire_Occurrence_Data_2000-2022.csv']

In [35]:
final_df = pd.read_csv("ODF_Fire_Occurrence_Data_2000-2022.csv")
final_df.head()

,Serial,FireCategory,FireYear,Area,DistrictName,UnitName,FullFireNumber,FireName,Size_class,EstTotalAcres,...,Industrial_Restriction,Ign_DateTime,ReportDateTime,Discover_DateTime,Control_DateTime,CreationDate,ModifiedDate,DistrictCode,UnitCode,DistFireNumber
0,108204,STAT,2017,EOA,Klamath-Lake,Lakeview,17-982068-18,Castle 483,A,NaN,...,NaN,NaN,08/08/2017 12:53:00 PM,NaN,NaN,08/08/2017 12:00:00 AM,08/08/2017 02:11:00 PM,98,982,068
1,68272,STAT,2003,NOA,North Cascade,Santiam,03-582216-04,Marion Forks Move Up,A,0.0,...,Unspecified,NaN,09/02/2003 12:00:00 AM,NaN,NaN,09/03/2003 01:43:00 PM,08/23/2011 04:20:00 PM,58,582,216
2,75461,STAT,2006,EOA,Klamath-Lake,Klamath,06-981055-07,BUCK,A,0.1,...,Lvl 4 Complete Shutdown,08/05/2006 03:00:00 PM,08/05/2006 03:45:00 PM,08/05/2006 03:42:00 PM,08/05/2006 06:00:00 PM,08/08/2006 07:43:00 PM,09/16/2006 04:31:00 PM,98,981,055
3,98874,STAT,2014,NOA,Forest Grove,Columbia City,14-532076-15,Hafferman Rd. #1,A,0.1,...,Lvl 2 Limited Shutdown,NaN,09/04/2014 02:20:00 PM,NaN,09/04/2014 02:40:00 PM,09/04/2014 12:00:00 AM,09/05/2014 11:28:00 AM,53,532,076
4,112552,STAT,2017,NOA,North Cascade,Santiam,17-582069-18,Lyons Preposition,A,NaN,...,NaN,NaN,09/12/2017 08:00:00 AM,NaN,NaN,08/29/2018 12:00:00 AM,08/29/2018 12:44:00 PM,58,582,069

In [36]:
final_df.describe()

,Serial,FireYear,EstTotalAcres,Protected_Acres,Lat_DD,Long_DD,Sec,DistrictCode,UnitCode
count,23490.000000,23490.00000,23411.000000,23490.000000,23480.000000,23480.000000,23478.000000,23490.000000,23490.000000
mean,90425.933461,2010.80132,270.802503,63.454008,43.718410,-122.258736,18.576753,77.754662,779.371052
std,20901.016028,6.73508,6816.736966,1973.577812,1.226385,1.707589,10.439507,14.618857,146.534574
min,57485.000000,2000.00000,0.000000,0.000000,41.089460,-124.983610,1.000000,51.000000,511.000000
25%,72508.500000,2005.00000,0.010000,0.010000,42.526093,-123.387420,10.000000,71.000000,711.000000
50%,88340.000000,2011.00000,0.100000,0.100000,43.581805,-122.847220,19.000000,73.000000,732.000000
75%,107432.500000,2017.00000,0.500000,0.350000,44.789518,-121.541827,28.000000,95.000000,954.000000
max,134021.000000,2022.00000,499945.000000,154570.000000,46.235000,-116.521110,36.000000,99.000000,991.000000

In [37]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23490 entries, 0 to 23489
Data columns (total 38 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Serial                  23490 non-null  int64
 1   FireCategory            23490 non-null  object
 2   FireYear                23490 non-null  int64
 3   Area                    23490 non-null  object
 4   DistrictName            23490 non-null  object
 5   UnitName                23490 non-null  object
 6   FullFireNumber          23490 non-null  object
 7   FireName                23490 non-null  object
 8   Size_class              23490 non-null  object
 9   EstTotalAcres           23411 non-null  float64
 10  Protected_Acres         23490 non-null  float64
 11  HumanOrLightning        23490 non-null  object
 12  CauseBy                 23362 non-null  object
 13  GeneralCause            23490 non-null  object
 14  SpecificCause           23266 non-null  object
 15  Cause_Comments          9805 non-null   object
 16  Lat_DD                  23480 non-null  float64
 17  Long_DD                 23480 non-null  float64
 18  LatLongDD               23480 non-null  object
 19  FO_LandOwnType          23490 non-null  object
 20  Twn                     23478 non-null  object
 21  Rng                     23475 non-null  object
 22  Sec                     23478 non-null  float64
 23  Subdiv                  23459 non-null  object
 24  LandmarkLocation        22208 non-null  object
 25  County                  23490 non-null  object
 26  RegUseZone              23440 non-null  object
 27  RegUseRestriction       23401 non-null  object
 28  Industrial_Restriction  23401 non-null  object
 29  Ign_DateTime            23396 non-null  object
 30  ReportDateTime          23490 non-null  object
 31  Discover_DateTime       23396 non-null  object
 32  Control_DateTime        23395 non-null  object
 33  CreationDate            23487 non-null  object
 34  ModifiedDate            23490 non-null  object
 35  DistrictCode            23490 non-null  int64
 36  UnitCode                23490 non-null  int64
 37  DistFireNumber          23490 non-null  object
dtypes: float64(5), int64(4), object(29)
memory usage: 6.8+ MB

In [39]:
final_df.shape

(23490, 38)

## Data Source

This data is sourced from the [Oregon Fire Department's survey of fires from 2000 to 2022.](https://data.oregon.gov/Natural-Resources/ODF-Fire-Occurrence-Data-2000-2022/fbwv-q84y/related_content)

Originally, it was simply gathered to determine causes of fire as well as point out the locations in which they occurred. Many of the data points pertain to cause, acres burned, protected acres burned, the date, as well as serial numbers, names of the fire and what units and districts related to them.